title: Corey Roth # your name (or website title) here
logo: "/images/Profile picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Veteran of the US Navy who has been working as a industrial electrician since separating from the Military.
  I decided to go back to school and pursue a Bachelor's Degree in computer science and I'm 
  looking forward to graduating on the fall and ready for a career change. 
  <br><br>
  <a href="https://www.linkedin.com/in/corey-roth-649ba3115/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
