title: Corey Roth # your name (or website title) here
logo: "/images/Profile picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Science Portfolio 
  <br><br>
  <a href="https://www.linkedin.com/in/corey-roth-649ba3115/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
